### ISSUE TITLE
File should not contain password

### ISSUE THREAD

**Issue by Pierstoval** [florentingarnier/blog#1]
These files contain a password:

https://github.com/florentingarnier/blog/blob/master/index.php#L14
https://github.com/florentingarnier/blog/blob/master/commentaire.php#L15

This is VERY insecure :smile:

**Comment by Lenezir** [comment]
Yes I already told him. :)

**Comment by florentingarnier** [comment]
Oh yes thanks

**Comment by Lenezir** [comment]
Be careful, your password is still there into the commits.
To remove it you have to delete completely your repository (in your local computer too) to remove all commits, then you have to create a new repository and you will be good. :+1:
